name: Python Flask API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check if vectorizers folder and files exist
      run: |
        if [ -d "vectorizers" ]; then
          echo "Vectorizers folder exists."
          if [ -f "vectorizers/tfidf_vectorizer.pkl" ]; then
            echo "TF-IDF Vectorizer found."
          else
            echo "TF-IDF Vectorizer not found!" >&2
            exit 1
          fi
        else
          echo "Vectorizers folder does not exist." >&2
          exit 1
        fi

    - name: Install specific cloudpickle version
      run: |
        pip install cloudpickle==2.2.1

    - name: Run tests with verbose output
      env:
        FLASK_ENV: 'testing'
      run: |
        pytest --maxfail=1 --disable-warnings -v