name: Python Flask API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check if vectorizers folder exists and list contents
      run: |
        if [ -d "vectorizers" ]; then
          echo "Listing vectorizers directory contents:"
          ls -al vectorizers/
        else
          echo "Vectorizers folder does not exist."
        fi

    - name: Run tests
      env:
        FLASK_ENV: 'testing'  # Add environment variable for Flask testing mode
      run: |
        pytest --maxfail=1 --disable-warnings